### ISSUE TITLE
Accordion needs a unique key prop

### ISSUE THREAD

**Issue by aaronshivers** [SnapITSolutions/snapit-hacktoberfest#100]
## Bug Report

**Current Behavior**
Each child in a list should have a unique "key" prop. Accordion does not follow this rule.

**Input Code**
https://github.com/SnapITSolutions/snapit-hacktoberfest/blob/b146819c8376530aef5308bbc70df18ba196c035/src/components/AccordionList.jsx#L13-L14

**Possible Solution**
Add a unique "key" prop to accordion.

**Additional context/Screenshots**
https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by AhmedAli125** [comment]
Hey @aaronshivers the PR is up against #101 please review the PR. Thankyou
