### ISSUE TITLE
Fix:  Login page needs MUI 

### ISSUE THREAD

**Issue by ssimmons05** [SnapITSolutions/snapit-hacktoberfest#121]
The Login.jsx file has some html elements that need to be updated to utilize MUI components instead.

https://mui.com/components/box/#main-content

https://github.com/SnapITSolutions/snapit-hacktoberfest/blob/5848694fff33ad0ef56e591cbea55aff8a36524c/src/pages/Login/Login.jsx#L5-L7

**Comment by yash-jain24** [comment]
i created a pull request, can you review it
