### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by aaronshivers** [SnapITSolutions/snapit-hacktoberfest#98]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As a user, I'd like to see a Projects page, so I can easily navigate to SnapIt open source projects.

**Comment by ssimmons05** [comment]
Can you make sure that you're on that branch - "Plvtinum-Contribution" and then type this in your terminal -  git push origin HEAD 

That should automatically create a remote on your own local repo and it will push your changes to it at the same time.   We should be able to merge it into our master branch from there.
